# Generated by Django 3.0.3 on 2020-03-29 16:26

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Img',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_url', models.ImageField(upload_to='img')),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'ordering': ['date'],
                'get_latest_by': 'date',
            },
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_name', models.CharField(help_text='image name of the prediction', max_length=20)),
                ('pred_num', models.IntegerField()),
                ('img', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='imgUp.Img')),
            ],
            options={
                'ordering': ['img'],
            },
        ),
        migrations.CreateModel(
            name='Detection',
            fields=[
                ('pred_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('box_id', models.CharField(help_text='ABCDE', max_length=1)),
                ('pred_cls', models.CharField(max_length=20)),
                ('score', models.FloatField()),
                ('xmin', models.IntegerField()),
                ('ymin', models.IntegerField()),
                ('xmax', models.IntegerField()),
                ('ymax', models.IntegerField()),
                ('context', models.TextField(help_text='A: 赤葉枯病 score: 0.995', max_length=100)),
                ('img_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imgUp.Prediction')),
            ],
            options={
                'ordering': ['img_name', 'box_id'],
            },
        ),
    ]
