# Generated by Django 3.0.3 on 2020-03-29 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imgUp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='img',
            name='img_name',
            field=models.CharField(default='unknow', help_text='image name of the prediction', max_length=20),
        ),
    ]
