# Generated by Django 3.0.3 on 2020-03-30 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imgUp', '0002_img_img_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detection',
            name='pred_id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='img',
            name='img_name',
            field=models.CharField(default='unknow', help_text='image name of the prediction', max_length=100),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='img_name',
            field=models.CharField(help_text='image name of the prediction', max_length=100),
        ),
    ]
