# Generated by Django 3.0.3 on 2020-03-31 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imgUp', '0003_auto_20200330_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='detection',
            name='html_file',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
