# Generated by Django 3.0.3 on 2020-04-01 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imgUp', '0004_detection_html_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='img',
            options={'get_latest_by': 'date', 'ordering': ['-date']},
        ),
    ]
