# Generated by Django 3.0.3 on 2020-07-23 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imgUp', '0005_auto_20200401_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='detection',
            name='feedback',
            field=models.TextField(blank=True, help_text='user feedback', max_length=100, null=True),
        ),
    ]
