# Generated by Django 3.0.3 on 2020-07-23 19:33

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imgUp', '0006_detection_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detection',
            name='feedback',
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('feedback', models.TextField(blank=True, help_text='user feedback', max_length=100, null=True)),
                ('pred', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imgUp.Detection')),
            ],
            options={
                'ordering': ['-date'],
                'get_latest_by': 'date',
            },
        ),
    ]
